version: "3.9"

services:
  api:
    build: .
    container_name: reservation_api
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app # for live reload (dev)
      - /app/node_modules
    working_dir: /app
    # Default command runs in production
    command: sh -c "npx prisma migrate deploy && node dist/main.js"
    # For development mode, override like this:
    # command: sh -c "npm run start:dev"

  db:
    image: postgres:15
    container_name: reservation_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
